version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: planning-poker-redis
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
